//go:build wasip1

/*
   Copyright The containerd Authors.

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/

// Code generated by gen-pkg-alias. DO NOT EDIT.

//nolint:revive
package api

import (
    "github.com/containerd/nri/pkg/api/v1alpha1"
)

// aliased constants from github.com/containerd/nri/pkg/api/v1alpha1
const (
    ContainerState_CONTAINER_CREATED    = v1alpha1.ContainerState_CONTAINER_CREATED
    ContainerState_CONTAINER_PAUSED     = v1alpha1.ContainerState_CONTAINER_PAUSED
    ContainerState_CONTAINER_RUNNING    = v1alpha1.ContainerState_CONTAINER_RUNNING
    ContainerState_CONTAINER_STOPPED    = v1alpha1.ContainerState_CONTAINER_STOPPED
    ContainerState_CONTAINER_UNKNOWN    = v1alpha1.ContainerState_CONTAINER_UNKNOWN
    DefaultPluginRegistrationTimeout    = v1alpha1.DefaultPluginRegistrationTimeout
    DefaultPluginRequestTimeout         = v1alpha1.DefaultPluginRequestTimeout
    DefaultSocketPath                   = v1alpha1.DefaultSocketPath
    Event_CREATE_CONTAINER              = v1alpha1.Event_CREATE_CONTAINER
    Event_LAST                          = v1alpha1.Event_LAST
    Event_POST_CREATE_CONTAINER         = v1alpha1.Event_POST_CREATE_CONTAINER
    Event_POST_START_CONTAINER          = v1alpha1.Event_POST_START_CONTAINER
    Event_POST_UPDATE_CONTAINER         = v1alpha1.Event_POST_UPDATE_CONTAINER
    Event_POST_UPDATE_POD_SANDBOX       = v1alpha1.Event_POST_UPDATE_POD_SANDBOX
    Event_REMOVE_CONTAINER              = v1alpha1.Event_REMOVE_CONTAINER
    Event_REMOVE_POD_SANDBOX            = v1alpha1.Event_REMOVE_POD_SANDBOX
    Event_RUN_POD_SANDBOX               = v1alpha1.Event_RUN_POD_SANDBOX
    Event_START_CONTAINER               = v1alpha1.Event_START_CONTAINER
    Event_STOP_CONTAINER                = v1alpha1.Event_STOP_CONTAINER
    Event_STOP_POD_SANDBOX              = v1alpha1.Event_STOP_POD_SANDBOX
    Event_UNKNOWN                       = v1alpha1.Event_UNKNOWN
    Event_UPDATE_CONTAINER              = v1alpha1.Event_UPDATE_CONTAINER
    Event_UPDATE_POD_SANDBOX            = v1alpha1.Event_UPDATE_POD_SANDBOX
    Event_VALIDATE_CONTAINER_ADJUSTMENT = v1alpha1.Event_VALIDATE_CONTAINER_ADJUSTMENT
    Field_Annotations                   = v1alpha1.Field_Annotations
    Field_Args                          = v1alpha1.Field_Args
    Field_BlockioClass                  = v1alpha1.Field_BlockioClass
    Field_CPUPeriod                     = v1alpha1.Field_CPUPeriod
    Field_CPUQuota                      = v1alpha1.Field_CPUQuota
    Field_CPURealtimePeriod             = v1alpha1.Field_CPURealtimePeriod
    Field_CPURealtimeRuntime            = v1alpha1.Field_CPURealtimeRuntime
    Field_CPUSetCPUs                    = v1alpha1.Field_CPUSetCPUs
    Field_CPUSetMems                    = v1alpha1.Field_CPUSetMems
    Field_CPUShares                     = v1alpha1.Field_CPUShares
    Field_CdiDevices                    = v1alpha1.Field_CdiDevices
    Field_CgroupsPath                   = v1alpha1.Field_CgroupsPath
    Field_CgroupsUnified                = v1alpha1.Field_CgroupsUnified
    Field_Devices                       = v1alpha1.Field_Devices
    Field_Env                           = v1alpha1.Field_Env
    Field_HugepageLimits                = v1alpha1.Field_HugepageLimits
    Field_IoPriority                    = v1alpha1.Field_IoPriority
    Field_MemDisableOomKiller           = v1alpha1.Field_MemDisableOomKiller
    Field_MemKernelLimit                = v1alpha1.Field_MemKernelLimit
    Field_MemLimit                      = v1alpha1.Field_MemLimit
    Field_MemReservation                = v1alpha1.Field_MemReservation
    Field_MemSwapLimit                  = v1alpha1.Field_MemSwapLimit
    Field_MemSwappiness                 = v1alpha1.Field_MemSwappiness
    Field_MemTCPLimit                   = v1alpha1.Field_MemTCPLimit
    Field_MemUseHierarchy               = v1alpha1.Field_MemUseHierarchy
    Field_Mounts                        = v1alpha1.Field_Mounts
    Field_Namespace                     = v1alpha1.Field_Namespace
    Field_None                          = v1alpha1.Field_None
    Field_OciHooks                      = v1alpha1.Field_OciHooks
    Field_OomScoreAdj                   = v1alpha1.Field_OomScoreAdj
    Field_PidsLimit                     = v1alpha1.Field_PidsLimit
    Field_RdtClass                      = v1alpha1.Field_RdtClass
    Field_Rlimits                       = v1alpha1.Field_Rlimits
    Field_SeccompPolicy                 = v1alpha1.Field_SeccompPolicy
    IOPrioClass_IOPRIO_CLASS_BE         = v1alpha1.IOPrioClass_IOPRIO_CLASS_BE
    IOPrioClass_IOPRIO_CLASS_IDLE       = v1alpha1.IOPrioClass_IOPRIO_CLASS_IDLE
    IOPrioClass_IOPRIO_CLASS_NONE       = v1alpha1.IOPrioClass_IOPRIO_CLASS_NONE
    IOPrioClass_IOPRIO_CLASS_RT         = v1alpha1.IOPrioClass_IOPRIO_CLASS_RT
    LogRequest_LEVEL_DEBUG              = v1alpha1.LogRequest_LEVEL_DEBUG
    LogRequest_LEVEL_ERROR              = v1alpha1.LogRequest_LEVEL_ERROR
    LogRequest_LEVEL_INFO               = v1alpha1.LogRequest_LEVEL_INFO
    LogRequest_LEVEL_UNSPECIFIED        = v1alpha1.LogRequest_LEVEL_UNSPECIFIED
    LogRequest_LEVEL_WARN               = v1alpha1.LogRequest_LEVEL_WARN
    PluginIdxEnvVar                     = v1alpha1.PluginIdxEnvVar
    PluginNameEnvVar                    = v1alpha1.PluginNameEnvVar
    PluginPluginAPIVersion              = v1alpha1.PluginPluginAPIVersion
    PluginSocketEnvVar                  = v1alpha1.PluginSocketEnvVar
    SELinuxRelabel                      = v1alpha1.SELinuxRelabel
    SecurityProfile_LOCALHOST           = v1alpha1.SecurityProfile_LOCALHOST
    SecurityProfile_RUNTIME_DEFAULT     = v1alpha1.SecurityProfile_RUNTIME_DEFAULT
    SecurityProfile_UNCONFINED          = v1alpha1.SecurityProfile_UNCONFINED
    ValidEvents                         = v1alpha1.ValidEvents
)

// aliased variables from github.com/containerd/nri/pkg/api/v1alpha1
var (
    ContainerState_name               = v1alpha1.ContainerState_name
    ContainerState_value              = v1alpha1.ContainerState_value
    ErrIntOverflow                    = v1alpha1.ErrIntOverflow
    ErrInvalidLength                  = v1alpha1.ErrInvalidLength
    ErrUnexpectedEndOfGroup           = v1alpha1.ErrUnexpectedEndOfGroup
    Event_name                        = v1alpha1.Event_name
    Event_value                       = v1alpha1.Event_value
    Field_name                        = v1alpha1.Field_name
    Field_value                       = v1alpha1.Field_value
    File_pkg_api_v1alpha1_api_proto   = v1alpha1.File_pkg_api_v1alpha1_api_proto
    IOPrioClass_name                  = v1alpha1.IOPrioClass_name
    IOPrioClass_value                 = v1alpha1.IOPrioClass_value
    LogRequest_Level_name             = v1alpha1.LogRequest_Level_name
    LogRequest_Level_value            = v1alpha1.LogRequest_Level_value
    SecurityProfile_ProfileType_name  = v1alpha1.SecurityProfile_ProfileType_name
    SecurityProfile_ProfileType_value = v1alpha1.SecurityProfile_ProfileType_value
)

// aliased types from github.com/containerd/nri/pkg/api/v1alpha1
type (
    CDIDevice                           = v1alpha1.CDIDevice
    CompoundFieldOwners                 = v1alpha1.CompoundFieldOwners
    ConfigureRequest                    = v1alpha1.ConfigureRequest
    ConfigureResponse                   = v1alpha1.ConfigureResponse
    Container                           = v1alpha1.Container
    ContainerAdjustment                 = v1alpha1.ContainerAdjustment
    ContainerEviction                   = v1alpha1.ContainerEviction
    ContainerState                      = v1alpha1.ContainerState
    ContainerUpdate                     = v1alpha1.ContainerUpdate
    CreateContainerRequest              = v1alpha1.CreateContainerRequest
    CreateContainerResponse             = v1alpha1.CreateContainerResponse
    Empty                               = v1alpha1.Empty
    Event                               = v1alpha1.Event
    EventMask                           = v1alpha1.EventMask
    Field                               = v1alpha1.Field
    FieldOwners                         = v1alpha1.FieldOwners
    Hook                                = v1alpha1.Hook
    Hooks                               = v1alpha1.Hooks
    HostFunctions                       = v1alpha1.HostFunctions
    HugepageLimit                       = v1alpha1.HugepageLimit
    IOPrioClass                         = v1alpha1.IOPrioClass
    KeyValue                            = v1alpha1.KeyValue
    LinuxCPU                            = v1alpha1.LinuxCPU
    LinuxContainer                      = v1alpha1.LinuxContainer
    LinuxContainerAdjustment            = v1alpha1.LinuxContainerAdjustment
    LinuxContainerUpdate                = v1alpha1.LinuxContainerUpdate
    LinuxDevice                         = v1alpha1.LinuxDevice
    LinuxDeviceCgroup                   = v1alpha1.LinuxDeviceCgroup
    LinuxIOPriority                     = v1alpha1.LinuxIOPriority
    LinuxMemory                         = v1alpha1.LinuxMemory
    LinuxNamespace                      = v1alpha1.LinuxNamespace
    LinuxPids                           = v1alpha1.LinuxPids
    LinuxPodSandbox                     = v1alpha1.LinuxPodSandbox
    LinuxResources                      = v1alpha1.LinuxResources
    LinuxSeccomp                        = v1alpha1.LinuxSeccomp
    LinuxSeccompArg                     = v1alpha1.LinuxSeccompArg
    LinuxSyscall                        = v1alpha1.LinuxSyscall
    LogRequest                          = v1alpha1.LogRequest
    LogRequest_Level                    = v1alpha1.LogRequest_Level
    Mount                               = v1alpha1.Mount
    OptionalBool                        = v1alpha1.OptionalBool
    OptionalFileMode                    = v1alpha1.OptionalFileMode
    OptionalInt                         = v1alpha1.OptionalInt
    OptionalInt32                       = v1alpha1.OptionalInt32
    OptionalInt64                       = v1alpha1.OptionalInt64
    OptionalString                      = v1alpha1.OptionalString
    OptionalUInt32                      = v1alpha1.OptionalUInt32
    OptionalUInt64                      = v1alpha1.OptionalUInt64
    OwningPlugins                       = v1alpha1.OwningPlugins
    POSIXRlimit                         = v1alpha1.POSIXRlimit
    Plugin                              = v1alpha1.Plugin
    PluginInstance                      = v1alpha1.PluginInstance
    PodSandbox                          = v1alpha1.PodSandbox
    PostCreateContainerRequest          = v1alpha1.PostCreateContainerRequest
    PostCreateContainerResponse         = v1alpha1.PostCreateContainerResponse
    PostStartContainerRequest           = v1alpha1.PostStartContainerRequest
    PostStartContainerResponse          = v1alpha1.PostStartContainerResponse
    PostUpdateContainerRequest          = v1alpha1.PostUpdateContainerRequest
    PostUpdateContainerResponse         = v1alpha1.PostUpdateContainerResponse
    PostUpdatePodSandboxRequest         = v1alpha1.PostUpdatePodSandboxRequest
    PostUpdatePodSandboxResponse        = v1alpha1.PostUpdatePodSandboxResponse
    RegisterPluginRequest               = v1alpha1.RegisterPluginRequest
    RemoveContainerRequest              = v1alpha1.RemoveContainerRequest
    RemoveContainerResponse             = v1alpha1.RemoveContainerResponse
    RemovePodSandboxRequest             = v1alpha1.RemovePodSandboxRequest
    RemovePodSandboxResponse            = v1alpha1.RemovePodSandboxResponse
    RunPodSandboxRequest                = v1alpha1.RunPodSandboxRequest
    RunPodSandboxResponse               = v1alpha1.RunPodSandboxResponse
    SecurityProfile                     = v1alpha1.SecurityProfile
    SecurityProfile_ProfileType         = v1alpha1.SecurityProfile_ProfileType
    ShutdownRequest                     = v1alpha1.ShutdownRequest
    ShutdownResponse                    = v1alpha1.ShutdownResponse
    StartContainerRequest               = v1alpha1.StartContainerRequest
    StartContainerResponse              = v1alpha1.StartContainerResponse
    StateChangeEvent                    = v1alpha1.StateChangeEvent
    StateChangeResponse                 = v1alpha1.StateChangeResponse
    StopContainerRequest                = v1alpha1.StopContainerRequest
    StopContainerResponse               = v1alpha1.StopContainerResponse
    StopPodSandboxRequest               = v1alpha1.StopPodSandboxRequest
    StopPodSandboxResponse              = v1alpha1.StopPodSandboxResponse
    SynchronizeRequest                  = v1alpha1.SynchronizeRequest
    SynchronizeResponse                 = v1alpha1.SynchronizeResponse
    UpdateContainerRequest              = v1alpha1.UpdateContainerRequest
    UpdateContainerResponse             = v1alpha1.UpdateContainerResponse
    UpdateContainersRequest             = v1alpha1.UpdateContainersRequest
    UpdateContainersResponse            = v1alpha1.UpdateContainersResponse
    UpdatePodSandboxRequest             = v1alpha1.UpdatePodSandboxRequest
    UpdatePodSandboxResponse            = v1alpha1.UpdatePodSandboxResponse
    User                                = v1alpha1.User
    ValidateContainerAdjustmentRequest  = v1alpha1.ValidateContainerAdjustmentRequest
    ValidateContainerAdjustmentResponse = v1alpha1.ValidateContainerAdjustmentResponse
)

// aliased functions from github.com/containerd/nri/pkg/api/v1alpha1
var (
    Bool                    = v1alpha1.Bool
    CheckPluginIndex        = v1alpha1.CheckPluginIndex
    ClearRemovalMarker      = v1alpha1.ClearRemovalMarker
    DupStringMap            = v1alpha1.DupStringMap
    DupStringSlice          = v1alpha1.DupStringSlice
    FileMode                = v1alpha1.FileMode
    FromOCIEnv              = v1alpha1.FromOCIEnv
    FromOCIHookSlice        = v1alpha1.FromOCIHookSlice
    FromOCIHooks            = v1alpha1.FromOCIHooks
    FromOCIIOPriorityClass  = v1alpha1.FromOCIIOPriorityClass
    FromOCILinuxDevices     = v1alpha1.FromOCILinuxDevices
    FromOCILinuxIOPriority  = v1alpha1.FromOCILinuxIOPriority
    FromOCILinuxNamespaces  = v1alpha1.FromOCILinuxNamespaces
    FromOCILinuxResources   = v1alpha1.FromOCILinuxResources
    FromOCILinuxSeccomp     = v1alpha1.FromOCILinuxSeccomp
    FromOCILinuxSeccompArgs = v1alpha1.FromOCILinuxSeccompArgs
    FromOCILinuxSyscalls    = v1alpha1.FromOCILinuxSyscalls
    FromOCIMounts           = v1alpha1.FromOCIMounts
    Int                     = v1alpha1.Int
    Int32                   = v1alpha1.Int32
    Int64                   = v1alpha1.Int64
    IsMarkedForRemoval      = v1alpha1.IsMarkedForRemoval
    MarkForRemoval          = v1alpha1.MarkForRemoval
    MustParseEventMask      = v1alpha1.MustParseEventMask
    NewCompoundFieldOwners  = v1alpha1.NewCompoundFieldOwners
    NewFieldOwners          = v1alpha1.NewFieldOwners
    NewHostFunctions        = v1alpha1.NewHostFunctions
    NewOwningPlugins        = v1alpha1.NewOwningPlugins
    ParseEventMask          = v1alpha1.ParseEventMask
    ParsePluginName         = v1alpha1.ParsePluginName
    RegisterPlugin          = v1alpha1.RegisterPlugin
    String                  = v1alpha1.String
    ToOCILinuxSeccompArgs   = v1alpha1.ToOCILinuxSeccompArgs
    ToOCILinuxSyscalls      = v1alpha1.ToOCILinuxSyscalls
    UInt32                  = v1alpha1.UInt32
    UInt64                  = v1alpha1.UInt64
)
