apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nri-plugin-template
spec:
  template:
    spec:
      containers:
        - name: plugin
          volumeMounts:
            - name: plugin-auth
              mountPath: /etc/containers/nri/auth
      volumes:
        # Inject authentication keys from secret.
        - name: plugin-auth
          projected:
            sources:
            - secret:
                name: test-auth
                items:
                  - key: private
                    path: private
                  - key: public
                    path: public
