apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - daemonset.yaml
images:
  - name: plugin
    newName: ghcr.io/containerd/nri/plugins/ulimit-adjuster
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: nri-plugin-ulimit-adjuster
