/*
   Copyright The containerd Authors.

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/

// Code generated by gen-pkg-alias. DO NOT EDIT.

//nolint:revive
package stub

import (
    "github.com/containerd/nri/pkg/stub/v1alpha1"
)

// aliased constants from github.com/containerd/nri/pkg/stub/v1alpha1
const (
    DefaultRegistrationTimeout = stub.DefaultRegistrationTimeout
    DefaultRequestTimeout      = stub.DefaultRequestTimeout
)

// aliased variables from github.com/containerd/nri/pkg/stub/v1alpha1
var (
    ErrNoService = stub.ErrNoService
)

// aliased types from github.com/containerd/nri/pkg/stub/v1alpha1
type (
    ConfigureInterface                   = stub.ConfigureInterface
    CreateContainerInterface             = stub.CreateContainerInterface
    EventMask                            = stub.EventMask
    Option                               = stub.Option
    Plugin                               = stub.Plugin
    PostCreateContainerInterface         = stub.PostCreateContainerInterface
    PostStartContainerInterface          = stub.PostStartContainerInterface
    PostUpdateContainerInterface         = stub.PostUpdateContainerInterface
    PostUpdatePodInterface               = stub.PostUpdatePodInterface
    RemoveContainerInterface             = stub.RemoveContainerInterface
    RemovePodInterface                   = stub.RemovePodInterface
    RunPodInterface                      = stub.RunPodInterface
    ShutdownInterface                    = stub.ShutdownInterface
    StartContainerInterface              = stub.StartContainerInterface
    StopContainerInterface               = stub.StopContainerInterface
    StopPodInterface                     = stub.StopPodInterface
    Stub                                 = stub.Stub
    SynchronizeInterface                 = stub.SynchronizeInterface
    UpdateContainerInterface             = stub.UpdateContainerInterface
    UpdatePodInterface                   = stub.UpdatePodInterface
    ValidateContainerAdjustmentInterface = stub.ValidateContainerAdjustmentInterface
)

// aliased functions from github.com/containerd/nri/pkg/stub/v1alpha1
var (
    New              = stub.New
    WithConnection   = stub.WithConnection
    WithDialer       = stub.WithDialer
    WithOnClose      = stub.WithOnClose
    WithPluginIdx    = stub.WithPluginIdx
    WithPluginName   = stub.WithPluginName
    WithSocketPath   = stub.WithSocketPath
    WithTTRPCOptions = stub.WithTTRPCOptions
)
