apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nri-plugin-v010-adapter
spec:
  template:
    spec:
      containers:
        - name: plugin
          image: "ghcr.io/containerd/nri/plugins/v010-adapter:unstable"
          imagePullPolicy: Always
          args:
            - "-idx"
            - "99"
            - "-name"
            - "v010-adapter"
          volumeMounts:
            - name: nri-socket
              mountPath: /var/run/nri/nri.sock
      volumes:
      - name: nri-socket
        hostPath:
          path: /var/run/nri/nri.sock
          type: Socket
